[project]
name = "ufc-prediction"
version = "0.1.0"
description = "UFC fight prediction analysis"
requires-python = ">=3.9"
dependencies = [
    "pandas",
    "numpy",
    "pyyaml",
    "antlr4-python3-runtime>=4.9.0",
    "pydantic>=1.8.0",
]